# This workflow will build a C++ project using g++
name: C++ Build with g++

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install MinGW (for g++)
      run: |
        choco install mingw
        echo "C:\tools\mingw64\bin" >> $env:GITHUB_PATH
    - name: Build C++ Project
      run: |
        $cppFiles = Get-ChildItem -Path ../../../src -Filter *.cs | ForEach-Object { $_.FullName }
        g++ -o output.exe -Wall -Wextra -O2 $cppFiles
    - name: Run Executable
      run: ./output.exe
