# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest  # Set the environment to Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.403'  # Use '7.0.x' to get the latest patch of .NET 7.0

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore  # Use Release configuration for builds

    - name: Run Tests
      run: dotnet test --configuration Release --no-build --verbosity normal  # Run tests with Release configuration

    - name: Publish
      run: dotnet publish --configuration Release --no-build -o ./output  # Optional: Publish the project

